{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
  name: {{ .Release.Name }}-secretproviderclass
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects:
    - secretName: {{ .Release.Name }}-secret
      type: secret
      data:
        {{- range .Values.secretProviderClass.objects }}
        - key: {{ .key }}
          objectName: {{ .objectName }}
       {{- end }}
  parameters:
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
       {{- end }}
    tenantId: {{ .Values.secretProviderClass.tenantId }}
{{- end }}
