services:
  #
  # SuPA
  #
  supa:
    image: ghcr.io/workfloworchestrator/supa:latest@sha256:a3363cf9326be86ff2a53427dc1c93a3d32b43f29d2782a05b7d9927f8a3ddc4
    configs:
      - source: supa.env
        target: /usr/local/etc/supa/supa.env
    volumes:
      - .:/usr/local/var
    ports:
      - "4321:4321"
    depends_on:
      create-database-folder:
        condition: service_completed_successfully
      polynsi:
        condition: service_started
  #
  # PolyNSI
  #
  polynsi:
    image: ghcr.io/workfloworchestrator/polynsi:latest@sha256:69327c8ad4fd2eec192efd7a2e84cebe41d20cdc6e43537f367dd1ce02ac503e
    ports:
      - "8443:8443"
    configs:
      - source: application.properties
        target: /usr/local/polynsi/application.properties
      - source: polynsi-keystore.jks
        target: /usr/local/polynsi/polynsi-keystore.jks
      - source: polynsi-truststore.jks
        target: /usr/local/polynsi/polynsi-truststore.jks
    volumes:
      - ./tmp:/tmp:rw
  #
  # create SuPA database folder
  #
  create-database-folder:
    image: 'busybox:latest@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616'
    command: ["sh", "-c", "test -d /usr/local/var/db || mkdir /usr/local/var/db"]
    volumes:
      - .:/usr/local/var
configs:
  supa.env:
    file: ./supa.env
  application.properties:
    file: ./application.properties
  polynsi-keystore.jks:
    file: ./polynsi-keystore.jks
  polynsi-truststore.jks:
    file: ./polynsi-truststore.jks
