services:
  #
  # SuPA
  #
  supa:
    image: ghcr.io/workfloworchestrator/supa:latest@sha256:ce553b8fb482287367fd34f5a6e6e35c4cbd2e2b7c5e21bc167968a8ccbe9062
    configs:
      - source: supa.env
        target: /usr/local/etc/supa/supa.env
    volumes:
      - .:/usr/local/var
    ports:
      - "4321:4321"
    depends_on:
      create-database-folder:
        condition: service_completed_successfully
      polynsi:
        condition: service_started
  #
  # PolyNSI
  #
  polynsi:
    image: ghcr.io/workfloworchestrator/polynsi:latest@sha256:69327c8ad4fd2eec192efd7a2e84cebe41d20cdc6e43537f367dd1ce02ac503e
    ports:
      - "8443:8443"
    configs:
      - source: application.properties
        target: /usr/local/polynsi/application.properties
      - source: polynsi-keystore.jks
        target: /usr/local/polynsi/polynsi-keystore.jks
      - source: polynsi-truststore.jks
        target: /usr/local/polynsi/polynsi-truststore.jks
    volumes:
      - ./tmp:/tmp:rw
  #
  # create SuPA database folder
  #
  create-database-folder:
    image: 'busybox:latest@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e'
    command: ["sh", "-c", "test -d /usr/local/var/db || mkdir /usr/local/var/db"]
    volumes:
      - .:/usr/local/var
configs:
  supa.env:
    file: ./supa.env
  application.properties:
    file: ./application.properties
  polynsi-keystore.jks:
    file: ./polynsi-keystore.jks
  polynsi-truststore.jks:
    file: ./polynsi-truststore.jks
