services:
  #
  # SuPA
  #
  supa:
    image: ghcr.io/workfloworchestrator/supa:latest@sha256:27a108b604921f8d136e03e0b44e7d942e9fb418178120a46f2d10ca588bb03c
    configs:
      - source: supa.env
        target: /usr/local/etc/supa/supa.env
    volumes:
      - .:/usr/local/var
    ports:
      - "4321:4321"
    depends_on:
      create-database-folder:
        condition: service_completed_successfully
      polynsi:
        condition: service_started
  #
  # PolyNSI
  #
  polynsi:
    image: ghcr.io/workfloworchestrator/polynsi:latest@sha256:a701cd3f6c39d8358cb270c9572998f5d71b8d98eaa849ca6e5eed8123aea1f5
    ports:
      - "8443:8443"
    configs:
      - source: application.properties
        target: /usr/local/polynsi/application.properties
      - source: polynsi-keystore.jks
        target: /usr/local/polynsi/polynsi-keystore.jks
      - source: polynsi-truststore.jks
        target: /usr/local/polynsi/polynsi-truststore.jks
    volumes:
      - ./tmp:/tmp:rw
  #
  # create SuPA database folder
  #
  create-database-folder:
    image: 'busybox:latest@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616'
    command: ["sh", "-c", "test -d /usr/local/var/db || mkdir /usr/local/var/db"]
    volumes:
      - .:/usr/local/var
configs:
  supa.env:
    file: ./supa.env
  application.properties:
    file: ./application.properties
  polynsi-keystore.jks:
    file: ./polynsi-keystore.jks
  polynsi-truststore.jks:
    file: ./polynsi-truststore.jks
