name: Unit tests
on:
  push:
  workflow_dispatch:

jobs:
  container_job:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: true
    container: ubuntu:latest@sha256:84e77dee7d1bc93fb029a45e3c6cb9d8aa4831ccfcc7103d36e876938d28895b
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.11.3"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt update
          apt install --no-install-recommends --yes bash curl git gpg ca-certificates # needed by codecov below
          uv sync --link-mode=copy --dev  # editable install so coverage can be generated

      - name: Run Unit tests
        run: uv run pytest --cov-report term-missing --cov-report=xml --cov=src tests

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
