# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Linting Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
      fail-fast: true

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.9"
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: |
          # export PIP_ROOT_USER_ACTION=ignore
          # pip install --no-cache-dir uv
          uv sync --link-mode=copy --dev

      - name: Ruff format
        run: |
          uv run ruff format src/supa tests

      - name: Ruff check
        run: |
          uv run ruff check src/supa tests

      - name: Mypy
        run: |
          # do not run mypy on both directories at the same time
          uv run mypy src/supa
          uv run mypy tests
